name: Deploy Resume Website  # This is just a label, you can name it anything

on:
  push:
    branches:
      - main        # Run this workflow every time you push to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest   # Use an Ubuntu machine to run the job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   # Get all your website files

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5   # Prepare GitHub Pages

      - name: Upload website files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .      # Take everything in your repository folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4     # Deploy your website live

